const Marque_Area_Home_Two = () => {
    return (
        <div className="marque-area-home-2">
            <div className="marque-group-home-2">
                <div className="marque-wrapper-1">
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                </div>
            </div>
            <div className="marque-group-home-2">
                <div className="marque-wrapper-2">
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                    <span>EVELOPMENT</span>
                    <span>STUDIO</span>
                    <span>STRATEGY</span>
                    <span>BRANDING</span>
                    <span>AGENCY</span>
                    <span>TYPHOGRAPHY</span>
                    <span>DESIGN</span>
                    <span>INTERACTION</span>
                </div>
            </div>
        </div>
    )
}
export default Marque_Area_Home_Two
